# Generated by Django 2.2.7 on 2019-11-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20191117_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_on', '-updated_on', '-pk')},
        ),
    ]
